
CREATE TABLE `qualitron` (
  `fecha` DATE ,
  `hora` TIME ,
  `turno` INT,
  `common5` VARCHAR(20),
  `common30` VARCHAR(20),
  `cinco_mins` INT,
  `treinta_mins` INT,
  `id` INT  AUTO_INCREMENT,
  `referencia_id` INT,
  `alfacer4_calidad_MANCHAS_pequeño_claro` FLOAT,
  `alfacer4_calidad_MANCHA_pequeño_oscuro` FLOAT ,
  `alfacer4_calidad_MANCHAS_grande_claro` FLOAT ,
  `alfacer4_calidad_MANCHAS_grande_oscuro` FLOAT ,
  `alfacer4_calidad_GOTAS_gota_pequeña` FLOAT ,
  `alfacer4_calidad_GOTAS_gota_grande` FLOAT ,
  `alfacer4_calidad_PUNTOS` FLOAT ,
  `alfacer4_calidad_BANDAS_vertical` FLOAT ,
  `alfacer4_calidad_BANDAS_horizontal` FLOAT ,
  `alfacer4_calidad_LINEA_DIGITAL` FLOAT ,
  `alfacer4_calidad_BORDES` FLOAT ,
  `alfacer4_calidad_GRIETA_INTERNA` FLOAT ,
  `alfacer4_calidad_GRIETA_LATERAL` FLOAT ,
  `alfacer4_calidad_ESQUINA_DESPORTILLADA` FLOAT ,
  `alfacer4_calidad_ESQUINA_ROTA` FLOAT ,
  `alfacer4_calidad_PERFIL` FLOAT ,
  `alfacer4_calidad_GLOBALES` FLOAT ,
  `alfacer4_calidad_SUPERFICIE_grumos` FLOAT ,
  `alfacer4_calidad_SUPERFICIE_incrustacion` FLOAT ,
  `alfacer4_calidad_SUPERFICIE_hendidura` FLOAT ,
  `alfacer4_calidad_SUPERFICIE_gran_incrustacion` FLOAT ,
  `alfacer4_calidad_SUPERFICIE_gran_hendidura` FLOAT ,
  `alfacer4_calidad_LUMINOSIDAD_pequeña` FLOAT ,
  `alfacer4_calidad_LUMINOSIDAD_grande` FLOAT ,
  `alfacer4_calidad_BANDAS` FLOAT ,
  `alfacer4_calidad_BORDES` FLOAT ,
  `alfacer4_calidad_GRIETA_INTERNA` FLOAT ,
  `alfacer4_calidad_GRIETA_LATERAL` FLOAT ,
  `alfacer4_calidad_ESQUINA_DESPORTILLADA` FLOAT ,
  `alfacer4_calidad_GLOBALES` FLOAT ,
  `alfacer4_calidad_SUPERFICIE_grumos` FLOAT ,
  `alfacer4_calidad_BORDES` FLOAT ,
  `alfacer4_calidad_GRIETA_LATERAL` FLOAT ,
  `alfacer4_calidad_ESQUINA_DESPORTILLADA` FLOAT ,
  `alfacer4_calidad_LUMINOSIDAD_pequeña` FLOAT ,
  `alfacer4_calidad_LUMINOSIDAD_grande` FLOAT ,
  `alfacer4_calidad_GLOBALES` FLOAT ,
  `alfacer4_calidad_GRIETA_INTERNA` FLOAT ,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`referencia_id`) REFERENCES `referencia`(`referencia_id`)
);